"""Exact-physics UDE sweep with an initially zero neural correction.

The data are generated by the complete Lotka--Volterra system. The learned
model contains that exact vector field plus a two-output neural correction,

    f_model(y) = f_true(y) + correction_nn(y).

The correction network is initialized to output exactly zero by using random
hidden layers and a zero final layer. Thus the initial continuous-time model is
already correct. Any nonzero correction learned from a fixed-step rollout loss
is a candidate solver-induced compensation.

This script mirrors the original fixed-physics sweep: full-batch Adam training,
fixed-step Euler/Heun/RK4 rollouts, paired seeds, and tight Diffrax evaluation.
It additionally reports the initial matched-solver loss, learned-correction
norms, continuous-vs-matched losses, and the leading Euler IMDE alignment.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import pickle
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from jax import config

config.update("jax_enable_x64", True)

import diffrax
import jax
import jax.nn as jnn
import jax.numpy as jnp
import matplotlib
import numpy as np
import optax
from jax import jit, lax, random, value_and_grad, vmap

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from solver import forward_euler, heun, rk4, roll_out


A = 1.0
B = 0.05
R = 1.5
Z = 0.03
C = 0.005

T_TRAIN = 5.0
T_EXTRAPOLATE = 20.0
BASE_DT = 0.05
BASE_TRAIN_STEPS = int(round(T_TRAIN / BASE_DT))
BASE_EXTRAPOLATE_STEPS = int(round(T_EXTRAPOLATE / BASE_DT))

TRAIN_INITIAL_CONDITIONS = jnp.array(
    [
        [15.0, 25.0],
        [10.0, 20.0],
        [20.0, 30.0],
        [12.0, 22.0],
        [18.0, 28.0],
        [8.0, 18.0],
        [22.0, 26.0],
        [16.0, 15.0],
    ],
    dtype=jnp.float64,
)
VALIDATION_INITIAL_CONDITIONS = jnp.array(
    [[17.0, 25.0], [10.0, 23.0], [19.0, 24.0]], dtype=jnp.float64
)

SOLVERS = {
    "forward_euler": forward_euler,
    "heun": heun,
    "rk4": rk4,
}
NOMINAL_ORDERS = {"forward_euler": 1, "heun": 2, "rk4": 4}
STATE_SCALE = jnp.array([50.0, 50.0], dtype=jnp.float64)


def progress(message: str) -> None:
    print(message, flush=True)


def true_rhs(state, params=None):
    del params
    prey, predator = state
    return jnp.array(
        [
            A * prey - B * prey * predator - C * prey**2,
            -R * predator + Z * prey * predator,
        ]
    )


def diffrax_true_rhs(_t, state, _args):
    return true_rhs(state)


def random_layer_params(input_size, output_size, key, scale):
    weight_key, bias_key = random.split(key)
    weights = scale * random.normal(weight_key, (output_size, input_size))
    bias = scale * random.normal(bias_key, (output_size,))
    return weights, bias


def init_zero_output_network(layer_sizes, key, hidden_scale=1e-2):
    """Random hidden features with an exactly zero final network output."""
    keys = random.split(key, len(layer_sizes) - 1)
    layers = [
        random_layer_params(input_size, output_size, layer_key, hidden_scale)
        for input_size, output_size, layer_key in zip(
            layer_sizes[:-2], layer_sizes[1:-1], keys[:-1]
        )
    ]
    final_input_size = layer_sizes[-2]
    final_output_size = layer_sizes[-1]
    layers.append(
        (
            jnp.zeros((final_output_size, final_input_size), dtype=jnp.float64),
            jnp.zeros((final_output_size,), dtype=jnp.float64),
        )
    )
    return layers


def correction_nn(state, nn_params):
    activation = state / STATE_SCALE
    for weights, bias in nn_params[:-1]:
        activation = jnn.swish(jnp.dot(weights, activation) + bias)
    final_weights, final_bias = nn_params[-1]
    return jnp.dot(final_weights, activation) + final_bias


def model_rhs(state, params):
    return true_rhs(state) + correction_nn(state, params["nn_params"])


def initial_params(seed: int, hidden_width: int, hidden_scale: float):
    return {
        "nn_params": init_zero_output_network(
            [2, hidden_width, hidden_width, 2],
            random.key(seed),
            hidden_scale=hidden_scale,
        )
    }


@dataclass(frozen=True)
class ReferenceData:
    train_ts: jax.Array
    extrapolate_ts: jax.Array
    train: jax.Array
    validation: jax.Array
    extrapolate: jax.Array
    observation_stride: int

    @property
    def observation_dt(self) -> float:
        return BASE_DT * self.observation_stride


def solve_true_reference(y0, ts, t1, rtol, atol):
    solution = diffrax.diffeqsolve(
        diffrax.ODETerm(diffrax_true_rhs),
        diffrax.Tsit5(),
        t0=0.0,
        t1=t1,
        dt0=min(1e-3, t1 / 1000.0),
        y0=y0,
        saveat=diffrax.SaveAt(ts=ts),
        stepsize_controller=diffrax.PIDController(rtol=rtol, atol=atol),
        max_steps=500_000,
    )
    return solution.ys


def make_reference_data(observation_stride: int, rtol: float, atol: float):
    if BASE_TRAIN_STEPS % observation_stride != 0:
        raise ValueError(
            f"observation_stride={observation_stride} must divide "
            f"BASE_TRAIN_STEPS={BASE_TRAIN_STEPS}."
        )
    if BASE_EXTRAPOLATE_STEPS % observation_stride != 0:
        raise ValueError(
            f"observation_stride={observation_stride} must divide "
            f"BASE_EXTRAPOLATE_STEPS={BASE_EXTRAPOLATE_STEPS}."
        )

    full_extrapolate_ts = jnp.linspace(
        0.0, T_EXTRAPOLATE, BASE_EXTRAPOLATE_STEPS + 1
    )
    full_train_ts = full_extrapolate_ts[: BASE_TRAIN_STEPS + 1]
    progress("[setup] generating clean reference trajectories with Diffrax")
    full_extrapolate = vmap(
        lambda y0: solve_true_reference(
            y0, full_extrapolate_ts, T_EXTRAPOLATE, rtol, atol
        )
    )(TRAIN_INITIAL_CONDITIONS)
    full_validation = vmap(
        lambda y0: solve_true_reference(y0, full_train_ts, T_TRAIN, rtol, atol)
    )(VALIDATION_INITIAL_CONDITIONS)

    selection = slice(None, None, observation_stride)
    return ReferenceData(
        train_ts=full_train_ts[selection],
        extrapolate_ts=full_extrapolate_ts[selection],
        train=full_extrapolate[:, : BASE_TRAIN_STEPS + 1, :][:, selection, :],
        validation=full_validation[:, selection, :],
        extrapolate=full_extrapolate[:, selection, :],
        observation_stride=observation_stride,
    )


def rollout_batch(y0s, h, rhs, params, num_steps, method):
    return vmap(lambda y0: roll_out(y0, h, rhs, params, num_steps, method))(y0s)


def tree_l2_norm(tree):
    leaves = jax.tree_util.tree_leaves(tree)
    return jnp.sqrt(sum(jnp.sum(leaf**2) for leaf in leaves))


def make_training_loss(method, ratio, data, residual_regularization):
    h = data.observation_dt / ratio
    num_steps = (data.train.shape[1] - 1) * ratio
    residual_states = data.train.reshape(-1, 2)

    def loss(parameters):
        prediction = rollout_batch(
            TRAIN_INITIAL_CONDITIONS,
            h,
            model_rhs,
            parameters,
            num_steps,
            method,
        )[:, ::ratio, :]
        rollout_mse = jnp.mean((prediction - data.train) ** 2)
        if residual_regularization == 0.0:
            return rollout_mse
        corrections = vmap(correction_nn, in_axes=(0, None))(
            residual_states, parameters["nn_params"]
        )
        return rollout_mse + residual_regularization * jnp.mean(corrections**2)

    return loss


def train_model(
    seed,
    method,
    ratio,
    data,
    num_epochs,
    step_size,
    chunk_size,
    patience,
    min_delta,
    hidden_width,
    hidden_scale,
    residual_regularization,
):
    h = data.observation_dt / ratio
    params = initial_params(seed, hidden_width, hidden_scale)
    initial_corrections = vmap(correction_nn, in_axes=(0, None))(
        data.train.reshape(-1, 2), params["nn_params"]
    )
    initial_correction_max_abs = float(jnp.max(jnp.abs(initial_corrections)))
    if initial_correction_max_abs != 0.0:
        raise RuntimeError(
            "Zero-output initialization failed: initial correction is nonzero."
        )
    loss_function = make_training_loss(
        method, ratio, data, residual_regularization
    )
    optimizer = optax.adam(step_size)
    opt_state = optimizer.init(params)

    @jit
    def loss_and_grad(parameters):
        loss_value, gradients = value_and_grad(loss_function)(parameters)
        return loss_value, gradients, tree_l2_norm(gradients)

    @jit
    def train_step(carry, _):
        parameters, optimizer_state = carry
        loss_value, gradients = value_and_grad(loss_function)(parameters)
        updates, optimizer_state = optimizer.update(
            gradients, optimizer_state, parameters
        )
        parameters = optax.apply_updates(parameters, updates)
        return (parameters, optimizer_state), (
            loss_value,
            tree_l2_norm(gradients),
        )

    @jit
    def train_chunk(parameters, optimizer_state):
        (parameters, optimizer_state), diagnostics = lax.scan(
            train_step,
            (parameters, optimizer_state),
            None,
            length=chunk_size,
        )
        return parameters, optimizer_state, diagnostics

    initial_loss_value, _, initial_gradient_norm = loss_and_grad(params)
    initial_loss_value = float(initial_loss_value)
    initial_gradient_norm = float(initial_gradient_norm)
    best_loss = initial_loss_value
    best_params = params
    best_epoch = 0
    history = [
        {
            "epoch": 0,
            "loss": initial_loss_value,
            "gradient_norm": initial_gradient_norm,
        }
    ]
    epochs_without_improvement = 0
    chunks = num_epochs // chunk_size

    for chunk_index in range(chunks):
        params, opt_state, diagnostics = train_chunk(params, opt_state)
        del diagnostics
        epoch = (chunk_index + 1) * chunk_size
        current_loss, _, current_gradient_norm = loss_and_grad(params)
        loss_value = float(current_loss)
        gradient_norm = float(current_gradient_norm)
        history.append(
            {
                "epoch": epoch,
                "loss": loss_value,
                "gradient_norm": gradient_norm,
            }
        )

        if math.isfinite(loss_value) and loss_value < best_loss - min_delta:
            best_loss = loss_value
            best_params = params
            best_epoch = epoch
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += chunk_size

        if patience > 0 and epochs_without_improvement >= patience:
            break
        if not math.isfinite(loss_value):
            break

    final_loss, _, final_gradient_norm = loss_and_grad(params)
    best_loss_recomputed, _, best_gradient_norm = loss_and_grad(best_params)
    return {
        "params": best_params,
        "final_params": params,
        "seed": seed,
        "training_method": method.__name__,
        "ratio": ratio,
        "h_model": h,
        "initial_loss": initial_loss_value,
        "initial_correction_max_abs": initial_correction_max_abs,
        "initial_gradient_norm": initial_gradient_norm,
        "best_loss": float(best_loss_recomputed),
        "best_gradient_norm": float(best_gradient_norm),
        "best_epoch": best_epoch,
        "final_loss": float(final_loss),
        "final_gradient_norm": float(final_gradient_norm),
        "epochs_completed": history[-1]["epoch"],
        "history": history,
    }


def solve_model_diffrax(y0, params, ts, t1, rtol, atol):
    def rhs(t, state, parameters):
        del t
        return model_rhs(state, parameters)

    solution = diffrax.diffeqsolve(
        diffrax.ODETerm(rhs),
        diffrax.Tsit5(),
        t0=0.0,
        t1=t1,
        dt0=min(1e-3, t1 / 1000.0),
        y0=y0,
        args=params,
        saveat=diffrax.SaveAt(ts=ts),
        stepsize_controller=diffrax.PIDController(rtol=rtol, atol=atol),
        max_steps=500_000,
    )
    return solution.ys


def solve_model_diffrax_batch(y0s, params, ts, t1, rtol, atol):
    return vmap(
        lambda y0: solve_model_diffrax(y0, params, ts, t1, rtol, atol)
    )(y0s)


def time_error_curves(prediction, target):
    square_error = (prediction - target) ** 2
    mse_by_time = jnp.mean(square_error, axis=(0, 2))
    relative_by_time = jnp.linalg.norm(
        prediction - target, axis=(0, 2)
    ) / (jnp.linalg.norm(target, axis=(0, 2)) + 1e-30)
    return np.asarray(mse_by_time), np.asarray(relative_by_time)


def instability_rate(prediction, threshold=1e6):
    prediction = np.asarray(prediction)
    bad = (
        ~np.isfinite(prediction).all(axis=(1, 2))
        | (prediction < 0).any(axis=(1, 2))
        | (np.abs(prediction) > threshold).any(axis=(1, 2))
    )
    return float(np.mean(bad))


def evaluation_states():
    prey_values = jnp.linspace(5.0, 25.0, 20)
    predator_values = jnp.linspace(10.0, 40.0, 20)
    prey_grid, predator_grid = jnp.meshgrid(prey_values, predator_values)
    return jnp.stack(
        [prey_grid.reshape(-1), predator_grid.reshape(-1)], axis=1
    )


def vector_field_metrics(params, training_method, h):
    states = evaluation_states()
    true_field = vmap(true_rhs)(states)
    corrections = vmap(correction_nn, in_axes=(0, None))(
        states, params["nn_params"]
    )
    model_field = true_field + corrections
    correction_norm = jnp.linalg.norm(corrections)
    true_norm = jnp.linalg.norm(true_field)
    metrics = {
        "correction_mse": float(jnp.mean(corrections**2)),
        "correction_rms": float(jnp.sqrt(jnp.mean(corrections**2))),
        "correction_relative_to_true_vf": float(
            correction_norm / (true_norm + 1e-30)
        ),
        "correction_prey_rms": float(jnp.sqrt(jnp.mean(corrections[:, 0] ** 2))),
        "correction_predator_rms": float(
            jnp.sqrt(jnp.mean(corrections[:, 1] ** 2))
        ),
        "model_vf_mse": float(jnp.mean((model_field - true_field) ** 2)),
        "model_vf_rel_error": float(
            jnp.linalg.norm(model_field - true_field) / (true_norm + 1e-30)
        ),
        "euler_imde_cosine_similarity": "",
        "euler_imde_magnitude_ratio": "",
        "euler_imde_relative_error": "",
    }

    if training_method == "forward_euler":
        jacobian = jax.jacfwd(true_rhs)
        leading_correction = vmap(
            lambda state: 0.5 * h * (jacobian(state) @ true_rhs(state))
        )(states)
        learned_flat = corrections.reshape(-1)
        theory_flat = leading_correction.reshape(-1)
        learned_norm = jnp.linalg.norm(learned_flat)
        theory_norm = jnp.linalg.norm(theory_flat)
        metrics.update(
            {
                "euler_imde_cosine_similarity": float(
                    jnp.dot(learned_flat, theory_flat)
                    / (learned_norm * theory_norm + 1e-30)
                ),
                "euler_imde_magnitude_ratio": float(
                    learned_norm / (theory_norm + 1e-30)
                ),
                "euler_imde_relative_error": float(
                    jnp.linalg.norm(learned_flat - theory_flat)
                    / (theory_norm + 1e-30)
                ),
            }
        )
    return metrics


def make_zero_correction_continuous_baseline(data, evaluation_rtol, evaluation_atol):
    train_prediction = vmap(
        lambda y0: solve_true_reference(
            y0,
            data.train_ts,
            T_TRAIN,
            evaluation_rtol,
            evaluation_atol,
        )
    )(TRAIN_INITIAL_CONDITIONS)
    validation_prediction = vmap(
        lambda y0: solve_true_reference(
            y0,
            data.train_ts,
            T_TRAIN,
            evaluation_rtol,
            evaluation_atol,
        )
    )(VALIDATION_INITIAL_CONDITIONS)
    extrapolate_prediction = vmap(
        lambda y0: solve_true_reference(
            y0,
            data.extrapolate_ts,
            T_EXTRAPOLATE,
            evaluation_rtol,
            evaluation_atol,
        )
    )(TRAIN_INITIAL_CONDITIONS)
    extrapolation_mask = np.asarray(data.extrapolate_ts) > T_TRAIN
    return {
        "initial_continuous_train_mse": float(
            jnp.mean((train_prediction - data.train) ** 2)
        ),
        "initial_continuous_validation_mse": float(
            jnp.mean((validation_prediction - data.validation) ** 2)
        ),
        "initial_continuous_extrapolation_mse": float(
            jnp.mean(
                (
                    extrapolate_prediction[:, extrapolation_mask, :]
                    - data.extrapolate[:, extrapolation_mask, :]
                )
                ** 2
            )
        ),
        "initial_continuous_final_mse": float(
            jnp.mean(
                (extrapolate_prediction[:, -1, :] - data.extrapolate[:, -1, :])
                ** 2
            )
        ),
    }


def evaluate_model(
    trained,
    data,
    continuous_baseline,
    evaluation_rtol,
    evaluation_atol,
):
    params = trained["params"]
    method = SOLVERS[trained["training_method"]]
    ratio = trained["ratio"]
    h = trained["h_model"]

    continuous_train = solve_model_diffrax_batch(
        TRAIN_INITIAL_CONDITIONS,
        params,
        data.train_ts,
        T_TRAIN,
        evaluation_rtol,
        evaluation_atol,
    )
    continuous_validation = solve_model_diffrax_batch(
        VALIDATION_INITIAL_CONDITIONS,
        params,
        data.train_ts,
        T_TRAIN,
        evaluation_rtol,
        evaluation_atol,
    )
    continuous_extrapolate = solve_model_diffrax_batch(
        TRAIN_INITIAL_CONDITIONS,
        params,
        data.extrapolate_ts,
        T_EXTRAPOLATE,
        evaluation_rtol,
        evaluation_atol,
    )

    train_steps = (data.train.shape[1] - 1) * ratio
    extrapolate_steps = (data.extrapolate.shape[1] - 1) * ratio
    matched_train = rollout_batch(
        TRAIN_INITIAL_CONDITIONS,
        h,
        model_rhs,
        params,
        train_steps,
        method,
    )[:, ::ratio, :]
    matched_extrapolate = rollout_batch(
        TRAIN_INITIAL_CONDITIONS,
        h,
        model_rhs,
        params,
        extrapolate_steps,
        method,
    )[:, ::ratio, :]

    extrapolation_mask = np.asarray(data.extrapolate_ts) > T_TRAIN
    continuous_train_mse = float(jnp.mean((continuous_train - data.train) ** 2))
    continuous_validation_mse = float(
        jnp.mean((continuous_validation - data.validation) ** 2)
    )
    continuous_extrapolation_mse = float(
        jnp.mean(
            (
                continuous_extrapolate[:, extrapolation_mask, :]
                - data.extrapolate[:, extrapolation_mask, :]
            )
            ** 2
        )
    )
    matched_train_mse = float(jnp.mean((matched_train - data.train) ** 2))
    matched_extrapolation_mse = float(
        jnp.mean(
            (
                matched_extrapolate[:, extrapolation_mask, :]
                - data.extrapolate[:, extrapolation_mask, :]
            )
            ** 2
        )
    )
    initial_loss = trained["initial_loss"]
    loss_reduction = initial_loss - matched_train_mse
    relative_reduction = loss_reduction / max(initial_loss, np.finfo(float).tiny)
    tiny = np.finfo(float).tiny

    row = {
        "experiment_kind": "exact_physics_zero_residual_sweep",
        "training_method": trained["training_method"],
        "nominal_order": NOMINAL_ORDERS[trained["training_method"]],
        "ratio": ratio,
        "observation_dt": data.observation_dt,
        "h_model": h,
        "seed": trained["seed"],
        "initial_matched_train_mse": initial_loss,
        "initial_correction_max_abs": trained["initial_correction_max_abs"],
        **continuous_baseline,
        "initial_gradient_norm": trained["initial_gradient_norm"],
        "best_loss": trained["best_loss"],
        "best_gradient_norm": trained["best_gradient_norm"],
        "best_epoch": trained["best_epoch"],
        "final_loss": trained["final_loss"],
        "final_gradient_norm": trained["final_gradient_norm"],
        "epochs_completed": trained["epochs_completed"],
        "matched_train_mse": matched_train_mse,
        "matched_loss_reduction": loss_reduction,
        "matched_loss_relative_reduction": relative_reduction,
        "continuous_train_mse": continuous_train_mse,
        "continuous_train_mse_increase_from_zero": (
            continuous_train_mse
            - continuous_baseline["initial_continuous_train_mse"]
        ),
        "continuous_validation_mse": continuous_validation_mse,
        "continuous_extrapolation_mse": continuous_extrapolation_mse,
        "continuous_final_mse": float(
            jnp.mean(
                (
                    continuous_extrapolate[:, -1, :]
                    - data.extrapolate[:, -1, :]
                )
                ** 2
            )
        ),
        "matched_extrapolation_mse": matched_extrapolation_mse,
        "matched_final_mse": float(
            jnp.mean(
                (matched_extrapolate[:, -1, :] - data.extrapolate[:, -1, :])
                ** 2
            )
        ),
        "continuous_over_matched_train_ratio": (
            continuous_train_mse / max(matched_train_mse, tiny)
        ),
        "continuous_instability_rate": instability_rate(continuous_extrapolate),
        "matched_instability_rate": instability_rate(matched_extrapolate),
        **vector_field_metrics(params, trained["training_method"], h),
    }
    mse_by_time, relative_by_time = time_error_curves(
        continuous_extrapolate, data.extrapolate
    )
    return row, {
        "continuous_extrapolation_mse_by_time": mse_by_time,
        "continuous_extrapolation_relative_error_by_time": relative_by_time,
    }


def write_csv(rows, path):
    if not rows:
        return
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def make_group_summary(rows):
    output = []
    for solver_name in SOLVERS:
        solver_rows = [row for row in rows if row["training_method"] == solver_name]
        ratios = sorted({int(row["ratio"]) for row in solver_rows})
        for ratio in ratios:
            selected = [row for row in solver_rows if int(row["ratio"]) == ratio]
            summary = {
                "training_method": solver_name,
                "nominal_order": NOMINAL_ORDERS[solver_name],
                "ratio": ratio,
                "h_model": float(selected[0]["h_model"]),
                "n_seeds": len(selected),
            }
            for metric in [
                "initial_matched_train_mse",
                "matched_train_mse",
                "initial_continuous_train_mse",
                "continuous_train_mse",
                "continuous_validation_mse",
                "continuous_extrapolation_mse",
                "correction_mse",
                "correction_rms",
                "correction_relative_to_true_vf",
                "model_vf_rel_error",
            ]:
                values = np.asarray([float(row[metric]) for row in selected])
                summary[f"{metric}_mean"] = float(np.mean(values))
                summary[f"{metric}_std"] = float(np.std(values, ddof=1)) if len(values) > 1 else 0.0
            output.append(summary)

    for solver_name in SOLVERS:
        selected = [row for row in output if row["training_method"] == solver_name]
        selected.sort(key=lambda row: float(row["h_model"]))
        hs = np.asarray([float(row["h_model"]) for row in selected])
        errors = np.asarray(
            [float(row["correction_relative_to_true_vf_mean"]) for row in selected]
        )
        usable = np.isfinite(errors) & (errors > 1e-16)
        slope = (
            float(np.polyfit(np.log(hs[usable]), np.log(errors[usable]), 1)[0])
            if np.count_nonzero(usable) >= 2
            else float("nan")
        )
        for row in selected:
            row["empirical_correction_order"] = slope
    return output


def plot_correction_vs_stepsize(group_rows, output_dir):
    fig, ax = plt.subplots(figsize=(7.5, 5.5))
    for solver_name in SOLVERS:
        selected = [
            row for row in group_rows if row["training_method"] == solver_name
        ]
        selected.sort(key=lambda row: float(row["h_model"]))
        if not selected:
            continue
        hs = np.asarray([float(row["h_model"]) for row in selected])
        means = np.asarray(
            [float(row["correction_relative_to_true_vf_mean"]) for row in selected]
        )
        stds = np.asarray(
            [float(row["correction_relative_to_true_vf_std"]) for row in selected]
        )
        ax.errorbar(
            hs,
            np.maximum(means, 1e-18),
            yerr=stds,
            marker="o",
            capsize=3,
            label=solver_name,
        )
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("training solver step size h")
    ax.set_ylabel("learned correction norm / true vector-field norm")
    ax.set_title("Spurious neural correction induced by training solver")
    ax.grid(True, which="both", alpha=0.3)
    ax.legend()
    fig.tight_layout()
    fig.savefig(output_dir / "correction_vs_stepsize_loglog.png", dpi=200)
    plt.close(fig)


def plot_matched_vs_continuous(rows, output_dir):
    fig, ax = plt.subplots(figsize=(7.5, 5.5))
    for solver_name in SOLVERS:
        selected = [row for row in rows if row["training_method"] == solver_name]
        if not selected:
            continue
        ax.scatter(
            [max(float(row["matched_train_mse"]), 1e-30) for row in selected],
            [max(float(row["continuous_train_mse"]), 1e-30) for row in selected],
            label=solver_name,
            alpha=0.8,
        )
    low, high = ax.get_xlim()
    diagonal_low = max(low, 1e-30)
    ax.plot([diagonal_low, high], [diagonal_low, high], "k--", linewidth=1)
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("matched-solver train MSE")
    ax.set_ylabel("Diffrax continuous train MSE")
    ax.set_title("Matched rollout fit versus continuous-model error")
    ax.grid(True, which="both", alpha=0.3)
    ax.legend()
    fig.tight_layout()
    fig.savefig(output_dir / "matched_vs_continuous_train_mse.png", dpi=200)
    plt.close(fig)


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).with_name("exact_physics_zero_residual_results"),
    )
    parser.add_argument(
        "--solvers",
        nargs="+",
        choices=list(SOLVERS),
        default=list(SOLVERS),
    )
    parser.add_argument("--ratios", nargs="+", type=int, default=[1, 2, 4])
    parser.add_argument("--seeds", nargs="+", type=int, default=[0, 1, 2, 3, 4])
    parser.add_argument("--observation-stride", type=int, default=1)
    parser.add_argument("--num-epochs", type=int, default=30_000)
    parser.add_argument("--step-size", type=float, default=3e-3)
    parser.add_argument("--chunk-size", type=int, default=50)
    parser.add_argument(
        "--patience",
        type=int,
        default=3_000,
        help="Epochs without a new chunk-end best; set 0 to disable.",
    )
    parser.add_argument("--min-delta", type=float, default=0.0)
    parser.add_argument("--hidden-width", type=int, default=64)
    parser.add_argument("--hidden-scale", type=float, default=1e-2)
    parser.add_argument(
        "--residual-regularization",
        type=float,
        default=0.0,
        help="Default zero: regularization would suppress the correction being measured.",
    )
    parser.add_argument("--reference-rtol", type=float, default=1e-12)
    parser.add_argument("--reference-atol", type=float, default=1e-12)
    parser.add_argument("--evaluation-rtol", type=float, default=1e-9)
    parser.add_argument("--evaluation-atol", type=float, default=1e-9)
    parser.add_argument(
        "--plots", action=argparse.BooleanOptionalAction, default=True
    )
    return parser.parse_args()


def validate_args(args):
    if any(ratio < 1 for ratio in args.ratios):
        raise ValueError("All ratios must be positive integers.")
    if args.observation_stride < 1:
        raise ValueError("observation_stride must be positive.")
    if args.num_epochs < 1 or args.chunk_size < 1:
        raise ValueError("num_epochs and chunk_size must be positive.")
    if args.num_epochs % args.chunk_size != 0:
        raise ValueError("num_epochs must be divisible by chunk_size.")
    if args.step_size <= 0:
        raise ValueError("step_size must be positive.")
    if args.residual_regularization < 0:
        raise ValueError("residual_regularization cannot be negative.")


def main():
    args = parse_args()
    validate_args(args)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    data = make_reference_data(
        args.observation_stride, args.reference_rtol, args.reference_atol
    )
    continuous_baseline = make_zero_correction_continuous_baseline(
        data, args.evaluation_rtol, args.evaluation_atol
    )
    progress(
        f"[setup] observation_dt={data.observation_dt:g}, "
        f"train_points={data.train.shape[1]}, output={args.output_dir}"
    )

    trained_runs = {}
    total_runs = len(args.solvers) * len(args.ratios) * len(args.seeds)
    run_index = 0
    for solver_name in args.solvers:
        method = SOLVERS[solver_name]
        for ratio in args.ratios:
            for seed in args.seeds:
                run_index += 1
                progress(
                    f"[train {run_index}/{total_runs}] solver={solver_name}, "
                    f"ratio={ratio}, h={data.observation_dt / ratio:g}, seed={seed}"
                )
                trained = train_model(
                    seed=seed,
                    method=method,
                    ratio=ratio,
                    data=data,
                    num_epochs=args.num_epochs,
                    step_size=args.step_size,
                    chunk_size=args.chunk_size,
                    patience=args.patience,
                    min_delta=args.min_delta,
                    hidden_width=args.hidden_width,
                    hidden_scale=args.hidden_scale,
                    residual_regularization=args.residual_regularization,
                )
                trained_runs[(seed, solver_name, ratio)] = trained
                progress(
                    f"[train {run_index}/{total_runs}] "
                    f"initial={trained['initial_loss']:.3e}, "
                    f"best={trained['best_loss']:.3e}, "
                    f"epoch={trained['best_epoch']}, "
                    f"grad={trained['best_gradient_norm']:.3e}"
                )

    rows = []
    curves = {}
    history_rows = []
    for evaluation_index, (key, trained) in enumerate(trained_runs.items(), start=1):
        seed, solver_name, ratio = key
        progress(
            f"[eval {evaluation_index}/{total_runs}] "
            f"solver={solver_name}, ratio={ratio}, seed={seed}"
        )
        row, run_curves = evaluate_model(
            trained,
            data,
            continuous_baseline,
            args.evaluation_rtol,
            args.evaluation_atol,
        )
        rows.append(row)
        curves[key] = run_curves
        for history_item in trained["history"]:
            history_rows.append(
                {
                    "seed": seed,
                    "training_method": solver_name,
                    "ratio": ratio,
                    "h_model": trained["h_model"],
                    **history_item,
                }
            )
        progress(
            f"[eval {evaluation_index}/{total_runs}] "
            f"matched={row['matched_train_mse']:.3e}, "
            f"continuous={row['continuous_train_mse']:.3e}, "
            f"correction_rel={row['correction_relative_to_true_vf']:.3e}"
        )

    group_rows = make_group_summary(rows)
    write_csv(rows, args.output_dir / "summary.csv")
    write_csv(group_rows, args.output_dir / "group_summary.csv")
    write_csv(history_rows, args.output_dir / "training_history.csv")
    with (args.output_dir / "details.pkl").open("wb") as handle:
        pickle.dump(
            {
                "trained": trained_runs,
                "rows": rows,
                "group_rows": group_rows,
                "curves": curves,
            },
            handle,
        )

    metadata = {
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "description": "Exact physics plus initially zero neural correction sweep",
        "true_parameters": {"a": A, "b": B, "r": R, "z": Z, "c": C},
        "train_horizon": T_TRAIN,
        "extrapolation_horizon": T_EXTRAPOLATE,
        "base_dt": BASE_DT,
        "jax_enable_x64": bool(jax.config.x64_enabled),
        "arguments": {
            key: str(value) if isinstance(value, Path) else value
            for key, value in vars(args).items()
        },
    }
    with (args.output_dir / "metadata.json").open("w") as handle:
        json.dump(metadata, handle, indent=2)

    if args.plots:
        plot_correction_vs_stepsize(group_rows, args.output_dir)
        plot_matched_vs_continuous(rows, args.output_dir)
    progress(f"[done] results written to {args.output_dir}")


if __name__ == "__main__":
    main()
